### PR TITLE
fix wrong namespace reference

### PR DESCRIPTION
**Pull request by martinpetrasch**

### CODE REVIEW

**Comment by nadar** [comment]
Please add a changelog entry and thanks for the fix

**Comment by TheMaaarc** [comment]
Looks good to me.

@nadar You okay with it?

**Comment by nadar** [comment]
@martinpetrasch btw how did you found this bug? This must be there since almost 1 year :-) thanks again

**Comment by martinpetrasch** [comment]
I wanted to use an Ajax callback function in a block. This calls the BlockController.

**Pull request merged**
