### PR TITLE
ensure getEnvOption('pageObject'') resolves the PageObject

### PR DESCRIPTION
**Pull request by nadar**
https://github.com/luyadev/luya-module-cms/issues/401#issuecomment-1930924994

### CODE REVIEW

**Comment by nadar** [comment]
@hbugdoll now it resolves the NavItemPage object, which is the expected as the context key is known as `pageObject` and not `navItemObject`. Feel free to review. I have also ajdust the docs for the upcoming changes => https://luya.io/guide/cms/blocks.html#env-context-information

**Comment by nadar** [comment]
@hbugdoll i'am going to merge, need to tag a fresh release. if there is anything left, please create a PR. thank you very much for all the hints and help.

**Comment by hbugdoll** [comment]
> @hbugdoll i'am going to merge, need to tag a fresh release. if there is anything left, please create a PR. thank you very much for all the hints and help.

I'm a little bit to late, my review is just finished. It's all ok.
Thank you for your patience.

**Comment by hbugdoll** [comment]
> I have also ajdust the docs for the upcoming changes => https://luya.io/guide/cms/blocks.html#env-context-information

> pageObject: Returns the [luya\cms\models\NavItemPage ](https://api.luya.io/luya-cms-models-navitempage.html)object where you can run [luya\cms\models\NavItemPage -> **getNavItem()**](https://api.luya.io/luya-cms-models-navitempage.html#getNavItem()-detail) to retrieve the [luya\cms\models\NavItem ](https://api.luya.io/luya-cms-models-navitem.html)object, from there its possible to run [luya\cms\models\NavItem -> **getNav()**](https://api.luya.io/luya-cms-models-navitem.html#getNav()-detail) to retrieve the [luya\cms\models\Nav](https://api.luya.io/luya-cms-models-nav.html)

We only have to adjust the docs again...
As I have learned now, `getNavItem()` and `getNav()` returns not the `NavItem` resp. `Nav` objects.

**Comment by nadar** [comment]
thats the relation loading concept uf yii2, i assume people are familiar with those concepts. We have to point to the relations getXYZ() method, as they exists in the docs: https://api.luya.io/luya-cms-models-navitempage.html#getNavItem()-detail

Or did i understand you wrong?

**Comment by nadar** [comment]
@hbugdoll but please feel free to extend and improve the docs, its always welcome 👍

**Comment by hbugdoll** [comment]
In my opinion it is misleading because you have to call `$this->getEnvOption('pageObject')->navItem->nav`
instead of `$this->getEnvOption('pageObject')->getNavItem()->getNav()`.

**Comment by nadar** [comment]
Sure, you can extend this. For me it was important to point into the api docs and i assume people understand the relation concept uf yii2. but please add some more extra text if you like 👍

**Pull request merged**
