### PR TITLE
Add query string to LangSwitcher

### LINKED ISSUE #220: LangSwitcher should keep query string in URL (or at least have a such option)
One of the typical scenarios on page is to update some model. In this case an URL looks like http://host/lang/module/controller/update?id=5.

Switching the language should keep the same form but change the labels and so on.

At present the widget drops a query string, so the URL becomes http://host/lang2/module/controller/update. It causes Bad Request since the id is missed.

LUYA Core Version: 1.0.20
LUYA CMS Version: 2.1.0

### PR DESCRIPTION
**Pull request by Antikon**
### What are you changing/introducing
Add a simple function appendQueryString() which gets query string from current request and append it to the link

### What is the reason for changing/introducing
Fix #220 

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Fixed issues  | #220

### CODE REVIEW

**Comment by Antikon** [comment]
Sorry for such a silly mistake!

I need an advise on Unit Tests. I am not good enough in them.

Currently, the LangSwitcher Tests rely on data from `cms_nav_item` table in `luya_env_phpunit` db. The data refer to only one language (en). So in tests we always have a second link to a German homepage. I need to add some data in `cms_nav_item` for another language to test the LangSwitcher  transitions between some internal pages (with and without query string).

What should I do?

**Comment by nadar** [comment]
In the next version of the core we have an append function:

https://github.com/luyadev/luya/blob/master/core/helpers/Url.php#L133-L169

Maybe we can use this one afterwards. Also we need a unit test.

in order to test only the lang switcher with sqlite, there is a test for that: https://github.com/luyadev/luya-module-cms/blob/master/tests/src/widgets/LangSwitcherSqliteTest.php

so you can just run: `./vendor/bin/phpunit tests/widgets/LangSwitcherSqliteTest.php` to only test that file and don't care about the rest.

**Comment by nadar** [comment]
@Antikon Is there something i can help? or should we close this PR?

**Comment by nadar** [comment]
I am going to close this PR because:

- The PR has no activity for a long time.
- The PR does not have Unit Tests.
- The PR is not valid.
- The PR author does not respond to questions are comments.

> If the author (you) or someone is picking up the PR again, feel free to reopen. We **don't want to wast the time you have spent on the PR**. Also if you need help please let us know. Its not our aim to close PR's but we want to keep the repository activity as clean as possible.

If you think this is still important or there are more/new informations. **Please reopen the PR and let us know**.

**Pull request closed without merging**
