### PR TITLE
Page properties

### PR DESCRIPTION
**Pull request by boehsermoe**
@nadar started with implementation for #159. At first only the migration, model and angular part. The other PHP stuff will come later.

I add the new model `NavItemProperty` with a relation to NavItem. Why I does not add more columns to the `cms_nav_item`? Because the properties should only be optional values e.g. `og:title` or canonical. And also the`cms_nav_item` would become too big.

Add new action `updateNavItemProperties` to angular controller and send it too the api (implementation will follow).

### CODE REVIEW

**Comment by nadar** [comment]
Thats a though one, in order to fix #159 i would just add a new image upload for a cms page within the seo section. Somewhere here:

bildschirmfoto 2018-11-23 um 20 52 11

Also the twitter card informations i would just add them here:

https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/base/Controller.php#L106-L116

hmmm.. what do you think?

**Comment by nadar** [comment]
Everything else outside this default seo scope should be done with cms page properties (https://luya.io/guide/app-cmsproperties) Maybe a out-of-the box "meta tag propertie" would be helpfull (like image property but for meta informations (https://luya.io/api/luya-admin-base-ImageProperty)).

**Comment by boehsermoe** [comment]
Oh yeah of course I forgot the the cms page properties 🤔... but we need a different property for each language. That´s not possible with the page properties if I see it correctly. 

The image upload makes more sense directly in the page info, I think too.

Register the meta tags is easy to append in https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/base/Controller.php#L106-L116

**Comment by nadar** [comment]
Its possible to have multi lingual page properties - so its possible.

> Register the meta tags is obviously easy 

Yes, this would be done very quickly, even canonical information (not sure, but maybe trough: https://www.yiiframework.com/doc/api/2.0/yii-web-request#getUrl()-detail)

So the image property could be a setting on the cms_nav_item, but this requires a next major release - so we would need two pullrequests. One which could be done now (adding twitter card infos and canonical) - a second one which then can be done when we switch to next major version 1.1

**Comment by nadar** [comment]
So i am really sorry you spend time on this pull request. Maybe next time we should discuss the solution in the issue first.

**Comment by boehsermoe** [comment]
>So the image property could be a setting on the cms_nav_item, but this requires a next major release - so we would need two pullrequests. One which could be done now (adding twitter card infos and canonical) - a second one which then can be done when we switch to next major version 1.1

Sound good.

> So i am really sorry you spend time on this pull request. Maybe next time we should discuss the solution in the issue first.

Yes I think so too. It was a too hasty action by me. But thank you to take time for it!

**Pull request closed without merging**
