### PR TITLE
Page permission with website scope

### PR DESCRIPTION
**Pull request by boehsermoe**
### What are you changing/introducing

Page permission with website collape

### What is the reason for changing/introducing

Not alle container was displayed on page permissions

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Review by nadar — CHANGES_REQUESTED** [review]
nice! thanks. i know there are no tests for the present code available, but could you please add some tests?

**Comment by boehsermoe** [comment]
@nadar I tried to exclude admin/views/ path from codeclimate but apparently this does not work.

**Comment by nadar** [comment]
I have added another website

image

Then i should see them here i assume?

image

**Comment by nadar** [comment]
(since you have used the same branch name, i could not checkout the changes. going to test again, i deleted the previous comment)

**Comment by nadar** [comment]
image

i used the internal available `collapse-container` directive, now it looks more consistent

**Comment by nadar** [comment]
Thanks for your work and time!

**Pull request merged**
