### PR TITLE
add missing env informations to block #401

### LINKED ISSUE #401: Some block env options are missing in admin context
### What steps will reproduce the problem?

According to https://luya.io/guide/cms/blocks.html#env-context-information you can retrieve env / context information via `$this->getEnvOption(...)` (in admin context).
In frontend context you have to call `$this->block->getEnvOption(...)` instead. BTW this hint is currently missing in the guide.

### What is the expected result?
- The env options in admin context are the same as in frontend context.

Frontend example &ndash; called `$this->block->getEnvOption(...)` inside `blocks/views/MyBlock.php`:
id=`5`
blockId=`13`
context=`frontend`
pageObject=`{`NavItem...`}`
isFirst=`true`
isLast=`false`
index=`1`
itemsCount=`3`
isPrevEqual=`false`
isNextEqual=`true`
equalIndex=`1`

### What do you get instead?
- In admin context the page object is missing and further options related to the block's position.

Admin example &ndash; called `$this->getEnvOption(...)` inside `blocks\MyBlock::admin()`:
id=`5`
blockId=`13`
context=`admin`
pageObject=`{}`
isFirst=
isLast=
index=
itemsCount=
isPrevEqual=
isNextEqual=
equalIndex=

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | Admin 5.0.0, CMS 5.0.0
| PHP Version      | 8.2/8.3
| Platform         | Apache
| Operating system | Linux Server/macOS

### PR DESCRIPTION
**Pull request by nadar**
closes #401

### CODE REVIEW

**Review by hbugdoll — COMMENTED** [review]
For env options `'index'`, `'itemsCount'`, `'isFirst'`, `'isLast'`, `'isPrevEqual'`, `'isNextEqual'` and `'equalIndex'` it's fine now.
But for env option `'pageObject'` https://github.com/luyadev/luya-module-cms/blob/1a867a84865992ed92e9ae1aab56b5094fe403e5/src/models/NavItemPage.php#L479 is still wrong &ndash; `NavItem` instead of `NavItemPage` is needed as third argument.

**Comment by hbugdoll** [comment]
I've made new unit tests for the envOptions: https://github.com/luyadev/luya-module-cms/commit/ef4efcd366a6572d4bd1098cb8b4f92fb9dd1ae5.

And they have proven their worth &ndash; my `'equalIndex'` iteration was wrong (post-increment vs. pre-increment), see https://github.com/luyadev/luya-module-cms/commit/2d3be0da2574b21f4fa29ab030b9e1470e9bca5d.

**Block Test**
- Added new `BlockTest::testBlockEnvOptions()`
- Enhanced  therefore `TestBlock::admin()`
  - Accessing and returning envOptions and unused config value
- Improved `BlockTest::testBlockValues()` (checking unused config value)

**Block Placeholder Iteration Test**

- Added new test `BlockPlaceholderIterationTest::testEnvOptionsPlaceholderIteration()`
  - 3 equal blocks on 1 page via fixtures
  - Checking envOptions in admin context via `NavItemPage::getPlaceholder()`
  - Checking envOptions in frontend context via `NavItemPage::renderPlaceholder()`
- Added therefore new testing block `TestingEnvOptionsBlock`
  - Accessing on envOptions in admin context inside `renderAdmin()`
  - Accessing on envOptions in frontend context inside `renderFrontend()` (JSON decoding/encoding is needed because of internal processing & concat)
- Completed access on all block models in `BlockPlaceholderIterationTest::testRenderPlaceholderIteration()` for sake of completeness

**Comment by nadar** [comment]
@hbugdoll i will merge this PR.. You can send then a PR with only the unit tests and the according fix. ok? Afterwards we will take a look at the page object in another PR.

**Comment by nadar** [comment]
@hbugdoll you can now create a fresh merge request using the latest master (don't forget to create a branch on your fork).

**Comment by hbugdoll** [comment]
> @hbugdoll you can now create a fresh merge request using the latest master (don't forget to create a branch on your fork).

Ok, done &rarr; #407

**Pull request merged**
